server:
  port: 8081

spring:
  application:
    name: income-manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.124:3306/meitq_swp_dy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Mysql@meitq2018
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 20000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
